### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by AngQin104** [xhongc/dj-chat#22]
执行“python manage.py runserver 8088”出错：

File "D:\MyDownloadTemplate\dj-chat-master\venv\lib\site-packages\channels\routing.py", line 31, in get_default_application
    raise ImproperlyConfigured("Cannot import ASGI_APPLICATION module %r" % path)
django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module 'dj_chat.routing'

**Comment by xhongc** [comment]
> 执行“python manage.py runserver 8088”出错：
> 
> File "D:\MyDownloadTemplate\dj-chat-master\venv\lib\site-packages\channels\routing.py", line 31, in get_default_application raise ImproperlyConfigured("Cannot import ASGI_APPLICATION module %r" % path) django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module 'dj_chat.routing'

是否安装成功依赖呢

**Comment by AngQin104** [comment]
> > 执行“python manage.py runserver 8088”出错：
> > File "D:\MyDownloadTemplate\dj-chat-master\venv\lib\site-packages\channels\routing.py", line 31, in get_default_application raise ImproperlyConfigured("Cannot import ASGI_APPLICATION module %r" % path) django.core.exceptions.ImproperlyConfigured: Cannot import ASGI_APPLICATION module 'dj_chat.routing'
> 
> 是否安装成功依赖呢

是的呢，刚才部分依赖文件安装失败导致的，全部依赖安装了就好了

**Comment by AngQin104** [comment]
可以运行了，但还是依赖文件问题重重，导致添加好友失败，作者能不能重新发布requirements.txt？谢谢

**Comment by AngQin104** [comment]
必须得用Python3.7

**Comment by xhongc** [comment]
> 可以运行了，但还是依赖文件问题重重，导致添加好友失败，作者能不能重新发布requirements.txt？谢谢

额，你不是已经成功运行 :(dog

**Comment by AngQin104** [comment]
> 

可以了，我刚开始用的Python3.8，改成3.7就可以了

**Comment by xhongc** [comment]
> 必须得用Python3.7



> > 
> 
> 可以了，我刚开始用的Python3.8，改成3.7就可以了

ok, 自己部署着玩吗？
