### ISSUE TITLE
supervisor.conf in Docker ?

### ISSUE THREAD

**Issue by prototypeSean** [xhongc/dj-chat#3]
Hi 先謝謝這份詳細的文件跟Demo, 幫助不小

想請問：
supervisor.conf 在部屬的時候，這份檔案沒有用到？ 沒看到你複製到docker裡面

**Comment by xhongc** [comment]
是的 ，正如你所见
supervisor 适用在手动部署的时候，
在docker部署我没有用到supervisor

**Comment by prototypeSean** [comment]
正想說我漏看了
volumes:
      - .:/dj-chat
這邊的設定我以為你把根目錄都放進 container 的 volume 就可以讓 supervisor 吃到 conf?

----------

那請問如果沒在 docker 環境中使用 supervisor 要怎麼處理多個 worker 的情況呢？

**Comment by xhongc** [comment]
> 正想說我漏看了
> volumes:
> - .:/dj-chat
> 這邊的設定我以為你把根目錄都放進 container 的 volume 就可以讓 supervisor 吃到 conf?
> 
> 那請問如果沒在 docker 環境中使用 supervisor 要怎麼處理多個 worker 的情況呢？

1, volumes:- .:/dj-chat 设置卷目录是为了更新代码不需要再次docker build一遍
2，多个worker吗，你的意思是gunicorn的多个worker吗，也是可以配置在参数或者配置文件中，supervisor使用它是为了守护daphne和gunicorn这两个进程，使其意外宕机能重启服务，而docker是可以设置--restart always 来保证镜像可以重启。
嗯，大概就是这样子的，希望对你有所帮助

**Comment by prototypeSean** [comment]
worker 似乎在 channel 3 文檔中沒有特別提到這概念還是被什麼其他的工具取代了（就是在懷疑好像是supervisoir）
我上次使用channel 是在17年左右 Channel 1 時候，也還沒用上 docker，
記得那時候要在開啟 nginx ＆ daphne 之後自己手動設定 worker 數量 （進程數量？) 
但是最近想回來用django 爬遍新版的文章都沒提到這件事，所以猜測應該是被supervisor取代了
但是不太確定所以對這東西設定一直很困惑
